version: '3'
services:
  db:
    container_name: db-test-spring
    image: 'test-spring/database:1'
    build: ./postgres
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
volumes:
  dbdata:
    driver: local